name: CI-CD-Pipeline-to-AWS-ElastickBeanstalk
env:
  EB_PACKAGE_S3_BACKET_NAME: ak-app-flask-packages
  EB_APPLICATION_NAME : "Flask"
  EB_ENVIRONMENT_NAME : "Flask-env"
  DEPLOY_PACKAGE_NAME : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME     : "eu-west-2"

on:
  push:
    branches: 
      - main
      
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      
      - name: Greate ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
          
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Copy Deploymant package to S3 bucket    
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BACKET_NAME }}/
        
      - name: Print Happy Message for CI finish
        run: echo "CI Pipline part Finished successfully!"
